### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [davgross/fitz-hugh-ludlow_the-hasheesh-eater#2]
General:

- [x] Commit the changes made by `se clean .`

- [x] Commit the changes made by `se semanticate .`

- [x] "Notes on the Way Upward", "Labyrinths and Guiding Threads", and "Ideal Men and Their Stimulants" look like [Afterwords](https://standardebooks.org/manual/1.7.0/single-page#3.3.1). Afterwords need `backmatter` and `afterword` semantics. These files also need to be renamed ([SEMOS 2.2.4.5](https://standardebooks.org/manual/1.7.0/single-page#2.2.4.5)).

- [x] It looks like you still need to modernize "hasheesh" as "hashish" throughout the book, including the book's title. You can commit these changes in an editorial commit. The easiest way to update the cover.svg and titlepage.svg is building another repository with the modernized spelling and copying and pasting the files into your working repository. Make sure to also change the title in the content.opf and colophon and add metadata with the archaic spelling ([SEMOS 9.4.4.1](https://standardebooks.org/manual/1.7.0/single-page#9.4.4.1)).

preface.xhtml:

- [x] The `<section>` element needs `preface` semantics.

introduction.xhtml:

- [x] The `<section>` element needs `introduction` semantics.

chapter-5.xhtml:

- [x] In the [Google Books scans](https://www.google.com/books/edition/The_Hasheesh_Eater/ZZARAAAAYAAJ?hl=en&gbpv=1), the paragraph that lint complains about does end with a period. There might be a typo in your physical copy.

endnotes.xhtml:

- [ ] In note 2, New York Tribune needs to be italicized with newspaper semantics.

- [x] In note 2, "To the Editor of the New York Tribune:" should go inside the letter's `<header>` element. Remove the `z3998:salutation` from the paragraph.

- [x] In note 2, "Sir" should be wrapped in a `<span epub:type="z3998:salutation">` element.

- [x] The signature also needs `z3998:sender` semantics.

local.css:

- [x] The epigraph requires some CSS ([SEMOS 7.4.1](https://standardebooks.org/manual/1.7.0/single-page#7.4.1) and [7.4.6.3](https://standardebooks.org/manual/1.7.0/single-page#7.4.6.3))

- [x] You are missing some of the letter CSS ([SEMOS 7.7](https://standardebooks.org/manual/1.7.0/single-page#7.7)).

- [x] You need to add CSS for the language tags:
```
@namespace xml "http://www.w3.org/XML/1998/namespace";

body [xml|lang]{
font-style: italic;
}
```

content.opf:

- [x] In the spine, the half title needs to be placed after the epigraph, preface, and introduction.

**Comment by PLP-Consulting** [comment]
OK: I think I've fixed these. `se lint` complains about unused CSS styles having to do with the epigraph styling and I'm not sure why. I think that's why I didn't have those styles in the CSS originally. I've put them back in and am ignoring the linter for now. @EmmaSweeney

**Comment by EmmaSweeney** [comment]
- [x] The second `<link>` element needs to be changed in order for the file to connect to the local.css. Make sure the top of the file looks like:
```
	<head>
		<title>Epigraph</title>
		<link href="../css/core.css" rel="stylesheet" type="text/css"/>
		<link href="../css/local.css" rel="stylesheet" type="text/css"/>
	</head>
```

- [x] It looks like you still need to italicize the New York Tribune in the endnotes. Meke sure to use [Standard Ebooks semantics vocabulary](https://standardebooks.org/vocab/1.0) ([SEMOS 4.2.3](https://standardebooks.org/manual/1.7.0/single-page#4.2.3)).

- [x] In the endnotes, remove the period after "Hashish In Hydrophobia".

- [x] To center "Hashish In Hydrophobia" in the letter, you can add the following CSS:
```
#note-2 header > p:first-child{
	margin-bottom: 1em;
	text-align: center;
}
```

**Comment by EmmaSweeney** [comment]
One last thing, commit the changes made by `se typogrify .` Word joiners are needed for the two-em dashes.

**Comment by PLP-Consulting** [comment]
@EmmaSweeney done
